Add "include synthetic members" to mapping stats & save options
FabricMC/Enigma pull request #309
Opened 2020-08-20 17:49 UTC by YanisBft

Also updated French translation
Closes #204 (even though the fix itself was pushed a while ago)

2020-08-20 17:56 UTC, Runemoro commented
The bug you linked isn't asking to include synthetics, it's saying synthetics are being incorrectly *included* (that the check isn't working properly)...

Why would anyone want to include synthetics, since those can't be mapped?

2020-08-20 18:17 UTC, YanisBft commented
The issue also asked for an option to ignore it or not. And synthetics can be mapped:
![image](https://user-images.githubusercontent.com/16228338/90809599-02960200-e322-11ea-9ee4-e5a38401281b.png)
The synthetic method in red on the screenshot isn't counted in stats, but would be if you select the option added in this PR

2020-08-20 19:11 UTC, Runemoro commented
But not the method name, only the parameter names. It should only count parameters to lambdas (but not bridges).

The issue is asking for an option to ignore it, **because the current check isn't working**. Making the current check optional only makes it worse.

2020-09-01 10:57 UTC, YanisBft commented
@Runemoro as there was a misunderstanding on my side, reworded to be an option to include synthetic parameters

2020-10-22 08:12 UTC, modmuss50 approved these changes

2020-10-22 19:36 UTC, 2xsaiko requested changes
Code looks good, some minor style things

2020-10-22 19:36 UTC, 2xsaiko commented on enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
> +		return swing.data().section("Mapping Stats").getString("Top-level package").orElse("");
Please use title case for these ("Top-level package" -> "Top-Level Package")

2020-10-22 19:36 UTC, 2xsaiko commented on enigma/src/main/resources/lang/en_us.json
> +	"menu.file.stats.synthetic_parameters": "Include synthetic parameters",
Same here, use title case (while you're at it, change the one for top-level package too)

2020-10-22 21:00 UTC, YanisBft commented
Fixed capitalization

2020-10-26 17:08 UTC, Runemoro approved these changes

2020-10-26 18:08 UTC, 2xsaiko approved these changes

2020-10-27 04:02 UTC, merged