Add ja_jp.json for Japanese
FabricMC/Enigma pull request #352
Opened 2021-02-22 23:23 UTC by Toshimichi0915

2021-02-22 23:52 UTC, modmuss50 approved these changes

2021-02-23 08:52 UTC, reo-ar requested changes

2021-02-23 08:52 UTC, reo-ar commented on enigma/src/main/resources/lang/ja_jp.json
> +	"javadocs.edit": "Javadocsを編集する",
Javadocsを編集する -> Javadocを編集する

2021-02-23 08:52 UTC, reo-ar commented on enigma/src/main/resources/lang/ja_jp.json
> +	"javadocs.instruction": "このJavadocsを編集する",
このJavadocsを編集する -> このJavadocを編集する

2021-02-23 08:52 UTC, reo-ar commented on enigma/src/main/resources/lang/ja_jp.json
> +	"message.edit_docs.text": "%s が %s のJavadocsを編集しました",
のJavadocsを編集しました -> のJavadocを編集しました

2021-02-23 08:52 UTC, reo-ar commented on enigma/src/main/resources/lang/ja_jp.json
> +	"menu.file.exit": "終了",
File Exit -> ファイルを閉じる

It's more of a close than an exit program it's an exit file more commonly found as "ファイルを閉じる" in programs

2021-02-23 08:56 UTC, reo-ar commented on enigma/src/main/resources/lang/ja_jp.json
> +	"menu.file.exit": "終了",
Edit: I'm not sure about the context of this, if this refers to exit program then "終了" is correct.

2021-02-23 09:02 UTC, Toshimichi0915 commented on enigma/src/main/resources/lang/ja_jp.json
> +	"menu.file.exit": "終了",
that message is used for the exit button of the program.
This doesn't need changing.

2021-02-23 09:06 UTC, 2xsaiko commented on enigma/src/main/resources/lang/ja_jp.json
> +	"menu.file.exit": "終了",
This is actually 'Exit' in the File menu which exits the program

2021-02-23 09:08 UTC, 2xsaiko approved these changes

2021-02-23 19:06 UTC, merged

2021-02-23 19:06 UTC, 2xsaiko commented
~~PR farmer~~

Thanks!