Migrate to FlatLaf
FabricMC/Enigma pull request #358
Opened 2021-03-15 11:43 UTC by Juuxel

Fixes #355.

- Replaces the Darcula look and feel with [FlatLaf](https://github.com/JFormDesigner/FlatLaf)'s Darcula colour scheme.
  - FlatLaf does not have the same rendering bugs with CJK characters (at least on Windows 10).
  - FlatLaf is also under Apache 2.0, so we can use it as a drop-in replacement. It also looks almost identical to Darcula with the Darcula colour scheme.
- Replaces Metal with FlatLaf Light as the default look and feel. Metal is provided as a new, separate theme option.
  - FlatLaf Light looks a lot better than Metal (especially as a default theme for a modern application), so I decided to use it as the default. Metal can still be used with the other options.

2021-03-15 15:34 UTC, i509VCB approved these changes

2021-03-15 16:58 UTC, liach approved these changes

2021-03-15 17:00 UTC, Juuxel commented
Note that the failing build is due to JCenter being down (proguard-base is only there so it can't be removed unless proguard-base is rehosted on the Fabric maven).

2021-03-15 17:02 UTC, liach commented
@Juuxel proguard base (releases only) are also available on maven central and sonatype oss. However, the previews (which supports up to java 16) is only available on bintray.

2021-03-15 17:03 UTC, liach commented
Wait, that's only core. Maybe we can just build it once and keep the built jar in the repo

2021-03-15 17:06 UTC, Juuxel commented
Yeah only the core is available on Central, see Guardsquare/proguard#54 (modmuss said that he can rehost it on the fabric maven so no need to store the jar here)

2021-03-15 18:06 UTC, YanisBft approved these changes
Nice!

2021-03-16 18:15 UTC, 2xsaiko requested changes
Looks good! I was expecting a lot more changes tbh :P

Although, there's one thing I noticed, looks like it comes with its own DPI scaling. This is how it looks like with 150% scaling on a 4k screen:

![image](https://user-images.githubusercontent.com/3987560/111358626-d7db1480-868a-11eb-84fa-5744347ef313.png)

The UiDefaultsScaler.updateAndApplyGlobalScaling call in ScaleUtil.applyScaling would have to not be executed for FlatLaf themes, commenting that call out makes it look okay for me.

Unless you can find a way to disable or override (with a custom value) FlatLaf's scaling, because without that call, it obviously doesn't respect the set scale in the enigma settings (for everything but fonts, those get and need to be applied separately).

2021-03-16 18:57 UTC, modmuss50 approved these changes
Tested seems to work fine on MacOS, the scaling might have been off a little but not as obvious as 2xsaiko's setup either way 👍

2021-03-16 19:49 UTC, 2xsaiko commented
It now works with the light theme, Darcula has issues with the font scaling for some reason (didn't test it before)...

![image](https://user-images.githubusercontent.com/3987560/111370866-07911900-8699-11eb-9870-81fb25c5b55e.png)

2021-03-16 21:38 UTC, Juuxel commented
Some other scaling problems I found:

- [ ] (Both) List spacing seems to be a bit off (not as extreme for me as the one in 2xsaiko's screenshot, but for example the tail of `g` cuts off)
- [ ] (Darcula) Radio button menu items are too small
- [ ] (Light) Menu buttons (the ones that open menus) are too small

2021-03-19 14:26 UTC, 2xsaiko approved these changes

2021-03-20 02:12 UTC, Runemoro approved these changes

2021-03-20 10:56 UTC, merged

2021-03-20 10:56 UTC, 2xsaiko commented
Thanks!