Add --single-class-tree argument that puts all classes into deobf panel & hides obf panel
FabricMC/Enigma pull request #406
Opened 2021-06-26 14:56 UTC by chylex

Parchment uses a jar with already remapped classes, but Enigma puts them into panel with obf classes which sorts classes by length. This option puts all classes into the deobf panel, and completely hides the obf panel.

2021-06-26 14:57 UTC, chylex commented
Fixed formatting.

2021-06-26 16:40 UTC, liach commented
hmm, can't this be part of the enigma profile than adding another parameter, making it hide obf panel if it's empty?

2021-06-26 17:16 UTC, 2xsaiko commented
Why would putting this in the enigma profile be better? As it is right now, it just looks like command line parameters with extra steps to me (especially if those parameters aren't complex like services).

2021-06-26 17:20 UTC, liach commented
having these in two places just complicates things up. The profile is supposed to take care of the configurations, isn't it? it's like arguing something should be in command line than server properties as it's a boolean/int simple field

2021-06-26 17:35 UTC, modmuss50 commented
I agree with @liach here I suggested putting <https://github.com/FabricMC/Enigma/commit/045a44a9ae2a70087e0d960a7196d1564c4c7ab1> into the profile json at the time. 

To me it seems like a good place to put project specific config, the services were just the start of this. CLI args are fine but we might end up with a whole bunch of them where a json file (espically with the editable types) would make more sense.

Im ok for this to go in now, but I do worry we might end up with 100s of cli args where it would be neater in a json file.

2021-06-26 21:18 UTC, 2xsaiko commented
I agree it's neater for sure, especially if you have a profile json inside whatever repo uses enigma and then have enigma load that which contains all the needed settings that it can load from one place.

In my opinion though, there's little to no benefit for it right now apart from that. To me, the current state of it just looks like glorified command line parameters in a file, especially since you specify the profile via a command line parameter. It just adds another layer of indirection that anything that wants to run enigma with custom settings (especially when those custom settings need to not always be the same) has to go through. Neither cmd nor bash has anything (tbh, Powershell probably has something) that lends itself well to building json files as far as I know (except a template that you then edit with `sed`, but come on). And even if you used something that has native json support like Python, what would happen is said script would put that finished json file into /tmp (hopefully under a unique name), then run enigma, passing the path to that file, then after enigma exits hopefully clean up after itself so the file doesn't stick around until the next reboot. Making a scriptable interface to programs has been figured out decades ago, and this isn't it.

Even for users who just want to run it with custom settings I'd say the command line parameters are significantly less involved, especially since the option parser has a very nice preexisting help text generator which helps a lot with being able to discover what options are available. Plus adding `-Epd` to the parameters to set up the configuration for "mojmap mode" is just a lot less to type, and a lot less to potentially get wrong. And if you wanted to run it more than once with the same settings, put the command line in a script (you can even write comments in there!)

I've seen a lot of programs that have both, though: essentially a configuration file and in addition to that, command line arguments that expose the same settings. I'd have nothing against that, because as a concept I don't think this is that bad of an idea, it's just very lacking for anything that _isn't_ some heavy framework like Gradle that wants to potentially use enigma, imo.

Unless of course, what the profiles were going for was that you could actually open/edit/save them from the enigma UI, like e.g. IDEA projects, in which case it would make a lot of sense to have that configuration as files only, and in that case I take everything back :P

Either way, I'll take a look at this tomorrow, I had absolutely no time do anything I actually wanted to do today, including reviewing this >_>

2021-06-26 23:15 UTC, liach commented
imo just hidr empty obf panel in enigma. for making obf panel empty, use an obf service instead.

2021-06-27 08:43 UTC, 2xsaiko commented
Isn't the option effectively useless without a service then? Why would you want to just hide the panel without listing the classes in it in the other one?

2021-06-27 09:21 UTC, 2xsaiko requested changes
- The label on the panel should say just "Classes" instead of "De-obfuscated Classes" if this option is enabled. The text is set in DeobfPanel.retranslateUi.
- I see now what happens where it crashes when renaming an obfuscated class in the panel. You're probably going to have to change Gui.onPanelRename so that instead of assuming that it will always find a class treating the old text from the rename box as a _deobfuscated_ name (which isn't the case here), that if it finds nothing, it will just treat the old name from the rename box as the obfuscated name.
  Replacing the .get() on the Optional with a isPresent check and if it's not present, setting obf = deobf _should_ work
  (This whole tree should probably be redone in the future so that it only uses obf entries internally and translates them to deobf only when displaying them, that sounds like a whole less lot of a hassle.)

2021-06-27 09:21 UTC, 2xsaiko commented on enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
> +		parser.accepts("single-class-tree", "Shows all classes in the de-obfuscated panel");
I'd rather say "List obfuscated and deobfuscated classes in a single panel" or "Unify the deobfuscated and obfuscated class panels" or something along those lines, it's not really the deobfuscated panel anymore if it contains everything (except in the code, but shhh don't tell em!) and there's no obfuscated panel to complement it

2021-06-28 10:06 UTC, 2xsaiko commented
Ahh, so just autohiding panels when they're empty? That would work, and definitely leaves more space when everything is mapped even for normal usage.

Though I could see users wondering where the panel with the obfuscated classes went and how to get it back when they don't know about that behavior, so maybe just remove the list and keep a label saying "No (de)obfuscated classes"? Not sure if that would be a problem.

2021-07-06 12:30 UTC, modmuss50 approved these changes
Pending changes suggested by @2xsaiko this looks good. 👍

2021-07-06 13:10 UTC, chylex commented on enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
> +	public Gui(EnigmaProfile profile, Set<EditableType> editableTypes, boolean singleClassTree) {
Committed, also checked that the gui survives calling it after the jar has loaded.

2021-07-06 13:15 UTC, liach approved these changes
Fantastic!

2021-07-06 21:53 UTC, 2xsaiko reviewed
Looks good! Please remove that comment though :P

2021-07-07 05:28 UTC, chylex commented
Comment begone :P prob good idea to squash it so you don't get my useless commit names

2021-07-07 07:18 UTC, 2xsaiko approved these changes
LGTM!

2021-07-08 14:28 UTC, merged