Update ja_jp.json
FabricMC/Enigma pull request #450
Opened 2022-06-10 16:36 UTC by Toshimichi0915

Everything in en_us.json has been translated into Japanese.

2022-06-10 17:40 UTC, apple502j requested changes

2022-06-10 17:40 UTC, apple502j commented on enigma/src/main/resources/lang/ja_jp.json
> +	"popup_menu.deobf_panel.collapse_all": "全て縮小する",
```suggestion
	"popup_menu.deobf_panel.collapse_all": "全て折りたたむ",
```

2022-06-10 17:40 UTC, apple502j commented on enigma/src/main/resources/lang/ja_jp.json
> +	"menu.search.class": "クラスを検索する",
Perhaps de-する these? These are menu items, which usually get 体言止めd

2022-06-10 17:40 UTC, apple502j commented on enigma/src/main/resources/lang/ja_jp.json
> +	"popup.copied": "コピーされました!",
```suggestion
	"popup.copied": "コピーしました!",
```

2022-06-10 17:40 UTC, apple502j commented on enigma/src/main/resources/lang/ja_jp.json
> +	"structure.options.obfuscation": "難読化の可視性",
This does not change the 可視性 of 難読化, it only hides/shows based on 難読化, better name?

2022-06-10 17:40 UTC, apple502j commented on enigma/src/main/resources/lang/ja_jp.json
> +	"structure.options.documentation": "ドキュメントの可視性",
Same goes here, this cannot hide javadoc

2022-06-11 02:51 UTC, Toshimichi0915 commented on enigma/src/main/resources/lang/ja_jp.json
> +	"structure.options.obfuscation": "難読化の可視性",
![image](https://user-images.githubusercontent.com/26406334/173169727-f6d59e30-5082-45e1-bccb-40e161c20c94.png)

I don't think 難読化の可視性 is that much confusing. "Obfuscation Visibility" is really translated into "難読化の可視性."

2022-06-11 07:48 UTC, Toshimichi0915 commented
squash & merge please

2022-06-12 12:21 UTC, merged

2022-06-12 12:21 UTC, 2xsaiko commented
Thanks!

> squash & merge please
FYI, you can do that yourself with `git rebase -i` (at least, that's one way to do it)